# LEVEL 1

## Task 1: Data Structure Basics

In [32]:
lst=[1,2,3]
print(type(lst))
print(lst)

<class 'list'>
[1, 2, 3]


In [34]:
lst.append(4)
lst

[1, 2, 3, 4]

In [40]:
st={2,4,6}
print(st)
print(type(st))

{2, 4, 6}
<class 'set'>


In [44]:
tup=(1,3,5)
print(tup)
print(type(tup))

(1, 3, 5)
<class 'tuple'>


In [46]:
dict={"a":1,"b":2}
print(dict)
print(type(dict))

{'a': 1, 'b': 2}
<class 'dict'>


In [50]:
dict.update({"c":3})
dict

{'a': 1, 'b': 2, 'c': 3}

## Task 2: NumPy Array Stats

In [53]:
import numpy as np

In [57]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
mean=np.mean(arr)
max_no=np.max(arr)
min_no=np.min(arr)
print(f"Mean:{mean}"+", "+f"Max: {max_no}"+", "+f"Min: {min_no}")

Mean:5.5, Max: 10, Min: 1


## Task 3: Pandas CSV Load

In [78]:
import pandas as pd

In [82]:
df=pd.read_csv(r"C:/Users/nithy/OneDrive/Desktop/SYNCNER/LEVEL 1/level 1.csv")
df

Name  Age
0    Sahana   21
1   Shalini   20
2   Karthik   23
3  Mukilesh   22
4    Nivash   22
5  Sharjana   24
6       Sri   25
7     Agnes   28
8      Suba   21

In [84]:
df.head(5)

Name  Age
0    Sahana   21
1   Shalini   20
2   Karthik   23
3  Mukilesh   22
4    Nivash   22

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    9 non-null      object
 1   Age     9 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes


In [92]:
df.describe()

Age
count   9.000000
mean   22.888889
std     2.472066
min    20.000000
25%    21.000000
50%    22.000000
75%    24.000000
max    28.000000

## Task 4: Dynamic Data Structure

In [15]:
my_dict={}
for i in range(3):
    key=input("Enter a string:")
    value=input("Enter an integer:")
    my_dict[key]=value
print(my_dict)

Enter a string: x
Enter an integer: 1
Enter a string: y
Enter an integer: 2
Enter a string: z
Enter an integer: 3


{'x': '1', 'y': '2', 'z': '3'}


## Task 5: NumPy Matrix Operations

In [17]:
# matrix addition
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
tot=np.add(a,b)
print(tot)

[[ 6  8]
 [10 12]]


In [5]:
#  dot product
product=np.dot(a,b)
print(product)

[[19 22]
 [43 50]]


In [15]:
# element-wise multiplication
prod=a*b
print(prod)

[[ 5 12]
 [21 32]]


In [7]:
# matrix multiplication
matmul=np.matmul(a,b)
print(matmul)

[[19 22]
 [43 50]]
